name: On  PR
on:
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - ".github/**"
      - "Dockerfile"

env:
  SERVICE_NAME: pairing-matrix

jobs:
  verification:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/${{ env.SERVICE_NAME }}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Run tests
        run: ./run.sh test
        working-directory: ${{ github.workspace }}/${{ env.SERVICE_NAME }}/

  dependabot:
    runs-on: ubuntu-20.04
    needs: verification
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Add reviewers and label for Major update
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-major'}}
        run: |
          gh pr edit "$PR_URL" --add-label "major-update"
          gh pr edit "$PR_URL" --add-reviewer "sumanmaity112"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
