name: verify

on:
  push:
    branches: [main]

env:
  SERVICE_NAME: pairing-matrix

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/${{ env.SERVICE_NAME }}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Run all tests
        run: ./run.sh test
        working-directory: ${{ github.workspace }}/${{ env.SERVICE_NAME }}/
